### ISSUE TITLE
Add explaination of how codepoint is calculated?

### ISSUE THREAD

**Issue by vinay-deshmukh** [Parkayun/base65536#6]
How is the codepoint calculated exactly?

**Comment by Parkayun** [comment]
It's fast when you check the code `https://github.com/Parkayun/base65536/blob/master/base65536/core.py#L115-L117`

Our document is `https://base65536.readthedocs.io/en/latest/`
Also you can see original detail in `https://github.com/qntm/base65536`

**Comment by vinay-deshmukh** [comment]
> https://github.com/Parkayun/base65536/blob/master/base65536/core.py#L115-L117

These lines show the calculation, but do not say why it was done?

> https://base65536.readthedocs.io/en/latest/

This only lists the usage, and doesn't explain why the following was done.

        code_point = BLOCK_START[b2] + b1
        stream.write(unichr(code_point))
